-- Task Reward platform PostgreSQL schema for Neon

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  openid VARCHAR(64) UNIQUE NOT NULL,
  unionid VARCHAR(64),
  nickname VARCHAR(100),
  avatar VARCHAR(255),
  phone VARCHAR(255),
  total_earnings NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  available_balance NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  frozen_balance NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  publish_permission SMALLINT NOT NULL DEFAULT 0,
  status SMALLINT NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_users_openid ON users (openid);
CREATE INDEX IF NOT EXISTS idx_users_phone ON users (phone);

CREATE TABLE IF NOT EXISTS user_identity_links (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  identity_type VARCHAR(32) NOT NULL,
  identity_hash VARCHAR(128) NOT NULL,
  identity_value VARCHAR(255),
  source VARCHAR(32),
  source_ref VARCHAR(255),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (identity_type, identity_hash)
);

CREATE INDEX IF NOT EXISTS idx_user_identity_links_user_id ON user_identity_links (user_id);
CREATE INDEX IF NOT EXISTS idx_user_identity_links_identity_type ON user_identity_links (identity_type);

CREATE TABLE IF NOT EXISTS user_risk_flags (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL UNIQUE,
  status SMALLINT NOT NULL DEFAULT 1,
  risk_reason VARCHAR(500) NOT NULL,
  risk_tags JSONB,
  source VARCHAR(32),
  blocked_at TIMESTAMP,
  cleared_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_user_risk_flags_status ON user_risk_flags (status);
CREATE INDEX IF NOT EXISTS idx_user_risk_flags_blocked_at ON user_risk_flags (blocked_at);

CREATE TABLE IF NOT EXISTS user_platform_cooldowns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  platform VARCHAR(32) NOT NULL,
  last_submission_id BIGINT,
  last_submission_at TIMESTAMP,
  cooldown_until TIMESTAMP,
  cooldown_months INTEGER NOT NULL DEFAULT 3,
  reason VARCHAR(500),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (user_id, platform)
);

CREATE INDEX IF NOT EXISTS idx_user_platform_cooldowns_user_id ON user_platform_cooldowns (user_id);
CREATE INDEX IF NOT EXISTS idx_user_platform_cooldowns_until ON user_platform_cooldowns (cooldown_until);

CREATE TABLE IF NOT EXISTS merchants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  company_name VARCHAR(200),
  contact_name VARCHAR(50),
  contact_phone VARCHAR(20),
  email VARCHAR(100),
  balance NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  status SMALLINT NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_merchants_username ON merchants (username);

CREATE TABLE IF NOT EXISTS merchant_staffs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  merchant_id BIGINT NOT NULL,
  username VARCHAR(50) NOT NULL,
  password VARCHAR(255) NOT NULL,
  nickname VARCHAR(100),
  role VARCHAR(20) NOT NULL DEFAULT 'operator',
  status SMALLINT NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (merchant_id, username)
);

CREATE INDEX IF NOT EXISTS idx_merchant_staffs_merchant_id ON merchant_staffs (merchant_id);
CREATE INDEX IF NOT EXISTS idx_merchant_staffs_role ON merchant_staffs (role);

CREATE TABLE IF NOT EXISTS tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  merchant_id BIGINT NOT NULL,
  platform VARCHAR(32) NOT NULL DEFAULT 'taobao',
  title VARCHAR(200) NOT NULL,
  description TEXT,
  reward_amount NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  total_quota INTEGER NOT NULL DEFAULT 0,
  remaining_quota INTEGER NOT NULL DEFAULT 0,
  search_keyword VARCHAR(100),
  shop_name VARCHAR(200),
  product_name VARCHAR(200),
  product_link VARCHAR(500),
  requirements JSONB,
  status SMALLINT NOT NULL DEFAULT 1,
  start_time TIMESTAMP,
  accept_start_time TIMESTAMP,
  end_time TIMESTAMP,
  start_notified_at TIMESTAMP,
  end_notified_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_tasks_merchant_id ON tasks (merchant_id);
CREATE INDEX IF NOT EXISTS idx_tasks_status ON tasks (status);
CREATE INDEX IF NOT EXISTS idx_tasks_start_time ON tasks (start_time);
CREATE INDEX IF NOT EXISTS idx_tasks_accept_start_time ON tasks (accept_start_time);
CREATE INDEX IF NOT EXISTS idx_tasks_status_end_time ON tasks (status, end_time);
CREATE INDEX IF NOT EXISTS idx_tasks_merchant_status_created_at ON tasks (merchant_id, status, created_at);

CREATE TABLE IF NOT EXISTS submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  platform VARCHAR(32) NOT NULL DEFAULT 'taobao',
  paid_amount NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  wechat_id VARCHAR(100),
  phone_number VARCHAR(255),
  order_number VARCHAR(100),
  screenshot_search VARCHAR(500),
  screenshot_shop_1 VARCHAR(500),
  screenshot_shop_2 VARCHAR(500),
  screenshot_shop_3 VARCHAR(500),
  screenshot_follow VARCHAR(500),
  screenshot_share VARCHAR(500),
  screenshot_detail VARCHAR(500),
  screenshot_cart VARCHAR(500),
  screenshot_paid_order VARCHAR(500),
  address_text TEXT,
  accepted_at TIMESTAMP,
  expires_at TIMESTAMP,
  released_at TIMESTAMP,
  release_reason VARCHAR(255),
  review_status SMALLINT NOT NULL DEFAULT 0,
  status SMALLINT NOT NULL DEFAULT 0,
  review_note VARCHAR(500),
  review_time TIMESTAMP,
  reject_reason VARCHAR(500),
  reviewed_at TIMESTAMP,
  submit_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  reward_amount NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (task_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_submissions_task_id ON submissions (task_id);
CREATE INDEX IF NOT EXISTS idx_submissions_user_id ON submissions (user_id);
CREATE INDEX IF NOT EXISTS idx_submissions_status ON submissions (status);
CREATE INDEX IF NOT EXISTS idx_submissions_review_status ON submissions (review_status);
CREATE INDEX IF NOT EXISTS idx_submissions_created_at ON submissions (created_at);
CREATE INDEX IF NOT EXISTS idx_submissions_task_status_created_at ON submissions (task_id, status, created_at);
CREATE INDEX IF NOT EXISTS idx_submissions_user_status_created_at ON submissions (user_id, status, created_at);
CREATE INDEX IF NOT EXISTS idx_submissions_task_review_submit ON submissions (task_id, review_status, submit_time);

CREATE TABLE IF NOT EXISTS earnings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  submission_id BIGINT,
  type SMALLINT NOT NULL,
  amount NUMERIC(10,2) NOT NULL,
  balance_after NUMERIC(10,2) NOT NULL,
  description VARCHAR(200),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_earnings_user_id ON earnings (user_id);
CREATE INDEX IF NOT EXISTS idx_earnings_type ON earnings (type);
CREATE INDEX IF NOT EXISTS idx_earnings_created_at ON earnings (created_at);

CREATE TABLE IF NOT EXISTS withdrawals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  amount NUMERIC(10,2) NOT NULL,
  fee NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  actual_amount NUMERIC(10,2) NOT NULL,
  withdraw_type SMALLINT NOT NULL DEFAULT 1,
  account_info VARCHAR(500),
  status SMALLINT NOT NULL DEFAULT 0,
  reject_reason VARCHAR(200),
  processed_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_withdrawals_user_id ON withdrawals (user_id);
CREATE INDEX IF NOT EXISTS idx_withdrawals_status ON withdrawals (status);

CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  operator_type VARCHAR(20) NOT NULL,
  operator_id BIGINT NOT NULL,
  action VARCHAR(50) NOT NULL,
  target_type VARCHAR(20) NOT NULL,
  target_id BIGINT NOT NULL,
  summary VARCHAR(255),
  detail JSONB,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_operator_id ON audit_logs (operator_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_target_type ON audit_logs (target_type);
CREATE INDEX IF NOT EXISTS idx_audit_logs_action ON audit_logs (action);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON audit_logs (created_at);

CREATE TABLE IF NOT EXISTS feedbacks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  user_nickname VARCHAR(100),
  user_avatar VARCHAR(255),
  category VARCHAR(50) NOT NULL DEFAULT 'general',
  content TEXT NOT NULL,
  contact_info VARCHAR(200),
  attachments JSONB,
  task_id BIGINT,
  status SMALLINT NOT NULL DEFAULT 0,
  reply_content TEXT,
  reply_user_type VARCHAR(20),
  reply_user_id BIGINT,
  reply_user_name VARCHAR(100),
  replied_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_feedbacks_user_id ON feedbacks (user_id);
CREATE INDEX IF NOT EXISTS idx_feedbacks_status ON feedbacks (status);
CREATE INDEX IF NOT EXISTS idx_feedbacks_created_at ON feedbacks (created_at);
CREATE INDEX IF NOT EXISTS idx_feedbacks_task_id ON feedbacks (task_id);

CREATE TABLE IF NOT EXISTS merchant_recharges (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  merchant_id BIGINT NOT NULL,
  amount NUMERIC(10,2) NOT NULL,
  payment_method SMALLINT,
  transaction_no VARCHAR(100),
  status SMALLINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_merchant_recharges_merchant_id ON merchant_recharges (merchant_id);

CREATE TABLE IF NOT EXISTS system_config (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  config_key VARCHAR(50) UNIQUE NOT NULL,
  config_value TEXT,
  description VARCHAR(200),
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS login_attempts (
  login_key VARCHAR(128) PRIMARY KEY,
  count INTEGER NOT NULL DEFAULT 0,
  locked_until TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_login_attempts_locked_until ON login_attempts (locked_until);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_users_updated_at') THEN
    CREATE TRIGGER trg_users_updated_at BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_user_identity_links_updated_at') THEN
    CREATE TRIGGER trg_user_identity_links_updated_at BEFORE UPDATE ON user_identity_links FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_user_risk_flags_updated_at') THEN
    CREATE TRIGGER trg_user_risk_flags_updated_at BEFORE UPDATE ON user_risk_flags FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_user_platform_cooldowns_updated_at') THEN
    CREATE TRIGGER trg_user_platform_cooldowns_updated_at BEFORE UPDATE ON user_platform_cooldowns FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_merchants_updated_at') THEN
    CREATE TRIGGER trg_merchants_updated_at BEFORE UPDATE ON merchants FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_merchant_staffs_updated_at') THEN
    CREATE TRIGGER trg_merchant_staffs_updated_at BEFORE UPDATE ON merchant_staffs FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_tasks_updated_at') THEN
    CREATE TRIGGER trg_tasks_updated_at BEFORE UPDATE ON tasks FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_submissions_updated_at') THEN
    CREATE TRIGGER trg_submissions_updated_at BEFORE UPDATE ON submissions FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_earnings_updated_at') THEN
    CREATE TRIGGER trg_earnings_updated_at BEFORE UPDATE ON earnings FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_withdrawals_updated_at') THEN
    CREATE TRIGGER trg_withdrawals_updated_at BEFORE UPDATE ON withdrawals FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_feedbacks_updated_at') THEN
    CREATE TRIGGER trg_feedbacks_updated_at BEFORE UPDATE ON feedbacks FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_merchant_recharges_updated_at') THEN
    CREATE TRIGGER trg_merchant_recharges_updated_at BEFORE UPDATE ON merchant_recharges FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_system_config_updated_at') THEN
    CREATE TRIGGER trg_system_config_updated_at BEFORE UPDATE ON system_config FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_login_attempts_updated_at') THEN
    CREATE TRIGGER trg_login_attempts_updated_at BEFORE UPDATE ON login_attempts FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END $$;

INSERT INTO system_config (config_key, config_value, description) VALUES
('min_withdrawal_amount', '10.00', 'Minimum withdrawal amount'),
('withdrawal_fee_rate', '0.01', 'Withdrawal fee rate'),
('platform_commission_rate', '0.10', 'Platform commission rate'),
('task_review_timeout', '24', 'Task review timeout in hours')
ON CONFLICT (config_key) DO UPDATE SET
  config_value = EXCLUDED.config_value,
  description = EXCLUDED.description;
