const express = require('express')
const cors = require('cors')

const app = express()

app.disable('x-powered-by')
app.use(cors())
app.use(express.json({ limit: '10mb' }))
app.use(express.urlencoded({ extended: true, limit: '10mb' }))

const route = (path, handler) => app.all(path, handler)

const health = require('./api/health')
const upload = require('./api/upload')
const userLogin = require('./api/user/login')
const userInfo = require('./api/user/info')
const userPhone = require('./api/user/phone')
const userEarnings = require('./api/user/earnings')
const userWithdrawals = require('./api/user/withdrawals')
const tasksIndex = require('./api/tasks/index')
const tasksId = require('./api/tasks/[id]')
const submissionsIndex = require('./api/submissions/index')
const submissionsMy = require('./api/submissions/my')
const submissionsId = require('./api/submissions/[id]')
const feedbacksIndex = require('./api/feedbacks/index')
const systemTaskLifecycle = require('./api/system/task-lifecycle')
const merchantLogin = require('./api/merchant/login')
const merchantTasks = require('./api/merchant/tasks/index')
const merchantSubmissions = require('./api/merchant/submissions/index')
const merchantSubmissionReview = require('./api/merchant/submissions/review')
const merchantUsers = require('./api/merchant/users/index')
const merchantStaffs = require('./api/merchant/staffs/index')
const merchantWithdrawals = require('./api/merchant/withdrawals/index')
const merchantRecharges = require('./api/merchant/recharges/index')
const merchantStats = require('./api/merchant/stats/index')
const merchantTodos = require('./api/merchant/todos')
const merchantRiskUsers = require('./api/merchant/risk-users/index')
const merchantAuditLogs = require('./api/merchant/audit-logs/index')
const merchantFeedbacks = require('./api/merchant/feedbacks/index')

route('/api/health', health)
route('/api/upload', upload)
route('/api/user/login', userLogin)
route('/api/user/info', userInfo)
route('/api/user/phone', userPhone)
route('/api/user/earnings', userEarnings)
route('/api/user/withdrawals', userWithdrawals)
route('/api/tasks', tasksIndex)
route('/api/tasks/:id', tasksId)
route('/api/submissions', submissionsIndex)
route('/api/submissions/my', submissionsMy)
route('/api/submissions/:id', submissionsId)
route('/api/feedbacks', feedbacksIndex)
route('/api/system/task-lifecycle', systemTaskLifecycle)
route('/api/merchant/login', merchantLogin)
route('/api/merchant/tasks', merchantTasks)
route('/api/merchant/submissions', merchantSubmissions)
route('/api/merchant/submissions/review', merchantSubmissionReview)
route('/api/merchant/users', merchantUsers)
route('/api/merchant/staffs', merchantStaffs)
route('/api/merchant/withdrawals', merchantWithdrawals)
route('/api/merchant/recharges', merchantRecharges)
route('/api/merchant/stats', merchantStats)
route('/api/merchant/todos', merchantTodos)
route('/api/merchant/risk-users', merchantRiskUsers)
route('/api/merchant/audit-logs', merchantAuditLogs)
route('/api/merchant/feedbacks', merchantFeedbacks)

app.use((req, res) => res.status(404).json({ code: 404, message: '接口不存在', data: null }))

module.exports = app
